### ISSUE TITLE
Journal functionality not working as expected

### ISSUE THREAD

**Issue by T-Whiz** [p4535992/foundryvtt-hidden-entity-links#3]
**Module Version:** v1.1.3

**Describe the bug**
Attempting to enable Hidden Entity Links functionality related to journals has no effect and displays the following error message "Hidden Entity Links: Error detected in module. It is likely this module has not been updated for FVTT Version 10. (See JS Console).

**To Reproduce**
1. Go to Module Settings for Hidden Entity Links and select the checkbox "Enable/disable the hidden functionality globally for Journal Entries".
2. Click on Save Changes
3. Refresh the screen

**Expected behavior**
Use case in v9 was for allowing players to view/interact with certain journal entries (and see it in the Journal sidebar) only when their token can see a corresponding Journal Note (map pin) for the journal entry (in this case a shop).

**Screenshots**
Attached screenshots and log.

**Browser:**
 - Microsoft Edge Version 105.0.1343.53 (Official build) (64-bit)

**Foundry Version:** 
Version 10 Build 286

**Game System:** 
DnD5e 2.0.3

**Additional context**
Recreated with only the following modules enabled: Hidden Entity Links, libWrapper (dependency), socketlib (dependency), and The Forge.
[tungstendragon.forge-vtt.com-1664839932953.log](https://github.com/p4535992/foundryvtt-hidden-entity-links/files/9701802/tungstendragon.forge-vtt.com-1664839932953.log)
![msedge_cMkpoglSTt](https://user-images.githubusercontent.com/101904996/193706542-f99c2e2f-266f-4be7-9798-c37d63de9883.png)

![Console Errors](https://user-images.githubusercontent.com/101904996/193706649-2b1b1af6-044e-48f0-8e35-a2c2531bc7a0.png)

**Comment by p4535992** [comment]
Should be fixed with 1.1.4

**Comment by p4535992** [comment]
I'll close the issue feel free to reopen if the issue persist.

**Comment by T-Whiz** [comment]
Apologies for the late reply, this has working perfectly since the fix, thanks very much.
