### ISSUE TITLE
[BUG] Roll Table buttons cut off

### ISSUE THREAD

**Issue by guldelox** [p4535992/foundryvtt-hidden-entity-links#4]
**Module Version:** v1.1.7

Roll table Update/Reset/Roll buttons cut off on the bottom, all rolltables open this way regardless of height. Moving or resizing the window fixes this.

**To Reproduce**
1. Open any rollable table
2. Observe bottom buttons cut off

**Expected behavior**
Buttons should be fully visible when window is opened.

**Screenshots**
![image](https://user-images.githubusercontent.com/67302749/236946002-e5dc437c-6cdd-4d28-a2b5-a9bfa38d498f.png)

**Browser:**
 - Chrome

**Foundry Version:** V10 Build 291

**Game System:** D&D5e 2.1.5

**Comment by p4535992** [comment]
This feature is been removed in favor of the module "Better Rolltables"
