### ISSUE TITLE
Other versions not available (broken manifest)

### ISSUE THREAD

**Issue by Weskernation** [p4535992/foundryvtt-hidden-entity-links#6]
On the official FoundryVTT module page
(https://foundryvtt.com/packages/hidden-entity-links)

the older versions e.g. V10. when clicking the manifest url of one other then the last version gives the latest version, not the older selected version. and the last version is not backward compatible

**Comment by p4535992** [comment]
Sorry for the late response. I will not suppor v10 or v9 related bug sorry.
